### PR TITLE
addition: human presence sensor support

### PR DESCRIPTION
**Pull request by sapireli**
added the tuya human presence sensor zy-m100 as an occupancy sensor, also added a light sensor as the zy-m100 has one built in.

### CODE REVIEW

**Comment by sapireli** [comment]
@hmenzagh if you could please merge

**Comment by hmenzagh** [comment]
@sapireli Will read the code tomorrow
First pass looks good, merging tomorrow I guess !

**Comment by sapireli** [comment]
Thank you @hmenzagh , its fully tested and working well for almost a month now.

**Comment by sapireli** [comment]
Just pinging to bump the version number and push it out. 🙏 thank you

**Review by hmenzagh — APPROVED** [review]

**Comment by hmenzagh** [comment]
@sapireli Sorry for the delay, package has been merged

**Pull request merged**
